table Costs

	measure EffectiveCostRunningTotal =
			
			CALCULATE(
				SUM('Costs'[EffectiveCost]),
				FILTER(
					ALLSELECTED('Costs'[ChargePeriodStart]),
					ISONORAFTER(DATEVALUE('Costs'[ChargePeriodStart]), DATEVALUE(MAX('Costs'[ChargePeriodStart])), DESC)
				)
			)
		formatString: #,0.00

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "RunningTotal",
				  "version": 0
				}

		changedProperty = FormatString

	measure x_CommitmentDiscountUtilization = IFERROR(SUM([x_CommitmentDiscountUtilizationAmount]) / SUM([x_CommitmentDiscountUtilizationPotential]), "")
		formatString: 0.0%;-0.0%;0.0%

		changedProperty = FormatString

	measure EffectiveCostVariance =
			
			VARX.P(
				KEEPFILTERS(VALUES(Costs[ChargePeriodStart])),
				CALCULATE(SUM([EffectiveCost]))
			)
		formatString: #,0.00

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "VariancePerCategory",
				  "version": 0
				}

		changedProperty = FormatString

	measure ChargePeriod = FORMAT(MIN([ChargePeriodStart]), IF(AND(FORMAT(MIN([ChargePeriodStart]), "yyyy") = FORMAT(UTCTODAY(), "yyyy"), FORMAT(MIN([ChargePeriodStart]), "yyyy") = FORMAT(MAX([ChargePeriodEnd])-1, "yyyy")), "Mmm dd", "Mmm dd, yyyy")) & IF(FORMAT(MIN([ChargePeriodStart]), "Mmm dd, yyyy") = FORMAT(MAX([ChargePeriodEnd])-1, "Mmm dd, yyyy"), "", "-" & FORMAT(MAX([ChargePeriodEnd]), IF(AND(FORMAT(MIN([ChargePeriodStart]), "yyyy") = FORMAT(UTCTODAY(), "yyyy"), FORMAT(MIN([ChargePeriodStart]), "yyyy") = FORMAT(MAX([ChargePeriodEnd])-1, "yyyy")), "Mmm dd", "Mmm dd, yyyy")))

	measure BillingPeriod = FORMAT(MIN([BillingPeriodStart]), "Mmm") & IF(FORMAT(MIN([BillingPeriodStart]), "Mmm yyyy") = FORMAT(MAX([BillingPeriodEnd])-1, "Mmm yyyy"), FORMAT(MIN([BillingPeriodStart]), " yyyy"), "-" & FORMAT(MAX([BillingPeriodEnd])-1, "Mmm yyyy"))

	measure x_TotalSavingsRunningTotal =
			
			CALCULATE(
				SUM('Costs'[x_TotalSavings]),
				FILTER(
					ALLSELECTED('Costs'[ChargePeriodStart]),
					ISONORAFTER(DATEVALUE('Costs'[ChargePeriodStart]), DATEVALUE(MAX('Costs'[ChargePeriodStart])), DESC)
				)
			)
		formatString: #,0.00

	measure x_CommitmentDiscountSavingsRunningTotal =
			
			CALCULATE(
				SUM('Costs'[x_CommitmentDiscountSavings]),
				FILTER(
					ALLSELECTED('Costs'[ChargePeriodStart]),
					ISONORAFTER(DATEVALUE('Costs'[ChargePeriodStart]), DATEVALUE(MAX('Costs'[ChargePeriodStart])), DESC)
				)
			)
		formatString: #,0.00

	measure x_NegotiatedDiscountSavingsRunningTotal =
			
			CALCULATE(
				SUM('Costs'[x_NegotiatedDiscountSavings]),
				FILTER(
					ALLSELECTED('Costs'[ChargePeriodStart]),
					ISONORAFTER(DATEVALUE('Costs'[ChargePeriodStart]), DATEVALUE(MAX('Costs'[ChargePeriodStart])), DESC)
				)
			)
		formatString: #,0.00

	measure x_EffectiveCostPerResource = SUM(Costs[EffectiveCost]) / COUNTROWS(VALUES(Costs[ResourceId]))

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure x_EffectiveSavingsRate = IFERROR(SUMX(FILTER(Costs, Costs[x_AmortizationClass] <> "Principal"), Costs[x_TotalSavings]) / SUMX(FILTER(Costs, Costs[x_AmortizationClass] <> "Principal"), Costs[ListCost]), "")
		formatString: 0.00%;-0.00%;0.00%

	measure x_CommitmentDiscountMeterCategory =
			
			VAR ComputeCondition = AND(SELECTEDVALUE(Costs[ProviderName]) = "Microsoft", SELECTEDVALUE(Costs[CommitmentDiscountCategory]) = "Spend")
			VAR ConcatenatedValues = CONCATENATEX(FILTER(VALUES(Costs[x_SkuMeterCategory]), AND(NOT ISBLANK(Costs[x_SkuMeterCategory]), Costs[x_SkuMeterCategory] <> "")), Costs[x_SkuMeterCategory], ", ")
			RETURN IF(ComputeCondition, "Compute", ConcatenatedValues)

	measure x_CommitmentDiscountMeterSubcategory =
			
			VAR ComputeCondition = AND(SELECTEDVALUE(Costs[ProviderName]) = "Microsoft", SELECTEDVALUE(Costs[CommitmentDiscountCategory]) = "Spend")
			VAR ConcatenatedValues = CONCATENATEX(FILTER(VALUES(Costs[x_SkuMeterSubcategory]), AND(NOT ISBLANK(Costs[x_SkuMeterSubcategory]), Costs[x_SkuMeterSubcategory] <> "")), Costs[x_SkuMeterSubcategory], ", ")
			RETURN IF(ComputeCondition, "Compute", ConcatenatedValues)

	measure x_SkuCoreCountMeasure = ```
			
			SUMX(
			    SUMMARIZE(
			        Costs,
			        Costs[ResourceId], 
			        "DistinctCoreCount", MAX(Costs[x_SkuCoreCount])
			    ),
			    [DistinctCoreCount]
			)
			```
		formatString: 0

	measure x_SkuLicenseQuantityMeasure = ```
			
			SUMX(
			    SUMMARIZE(
			        Costs,
			        Costs[ResourceId], 
			        "DistinctCoreCount", MAX(Costs[x_SkuLicenseQuantity])
			    ),
			    [DistinctCoreCount]
			)
			```
		formatString: 0

	column AvailabilityZone
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: AvailabilityZone

		annotation SummarizationSetBy = Automatic

	column BilledCost
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: BilledCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BillingAccountId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: BillingAccountId

		annotation SummarizationSetBy = Automatic

	column BillingAccountName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: BillingAccountName

		annotation SummarizationSetBy = Automatic

	column BillingAccountType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: BillingAccountType

		annotation SummarizationSetBy = Automatic

	column BillingCurrency
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: BillingCurrency

		annotation SummarizationSetBy = Automatic

	column BillingPeriodEnd
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: BillingPeriodEnd

		annotation SummarizationSetBy = Automatic

	column BillingPeriodStart
		dataType: dateTime
		formatString: Mmm yyyy
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: BillingPeriodStart

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column ChargeCategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ChargeCategory

		annotation SummarizationSetBy = Automatic

	column ChargeClass
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ChargeClass

		annotation SummarizationSetBy = Automatic

	column ChargeDescription
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ChargeDescription

		annotation SummarizationSetBy = Automatic

	column ChargeFrequency
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ChargeFrequency

		annotation SummarizationSetBy = Automatic

	column ChargePeriodEnd
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: ChargePeriodEnd

		annotation SummarizationSetBy = Automatic

	column ChargePeriodStart
		dataType: dateTime
		formatString: Mmm d, yyyy
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: ChargePeriodStart

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column CommitmentDiscountCategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CommitmentDiscountCategory

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CommitmentDiscountId

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CommitmentDiscountName

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountStatus
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CommitmentDiscountStatus

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CommitmentDiscountType

		annotation SummarizationSetBy = Automatic

	column ConsumedQuantity
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: ConsumedQuantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ConsumedUnit
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ConsumedUnit

		annotation SummarizationSetBy = Automatic

	column ContractedCost
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: ContractedCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ContractedUnitPrice
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: ContractedUnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveCost
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: EffectiveCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InvoiceIssuerName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: InvoiceIssuerName

		annotation SummarizationSetBy = Automatic

	column ListCost
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: ListCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListUnitPrice
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: ListUnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PricingCategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: PricingCategory

		annotation SummarizationSetBy = Automatic

	column PricingQuantity
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: PricingQuantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PricingUnit
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: PricingUnit

		annotation SummarizationSetBy = Automatic

	column ProviderName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ProviderName

		annotation SummarizationSetBy = Automatic

	column PublisherName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: PublisherName

		annotation SummarizationSetBy = Automatic

	column RegionId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: RegionId

		annotation SummarizationSetBy = Automatic

	column RegionName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: RegionName

		annotation SummarizationSetBy = Automatic

	column ResourceId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: distinctCount
		sourceColumn: ResourceId

		annotation SummarizationSetBy = User

	column ResourceName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ResourceName

		annotation SummarizationSetBy = Automatic

	column ResourceType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: distinctCount
		sourceColumn: ResourceType

		annotation SummarizationSetBy = User

	column ServiceCategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ServiceCategory

		annotation SummarizationSetBy = Automatic

	column ServiceName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ServiceName

		annotation SummarizationSetBy = Automatic

	column SkuId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SkuId

		annotation SummarizationSetBy = Automatic

	column SkuPriceId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SkuPriceId

		annotation SummarizationSetBy = Automatic

	column SubAccountId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SubAccountId

		annotation SummarizationSetBy = Automatic

	column SubAccountName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SubAccountName

		annotation SummarizationSetBy = Automatic

	column SubAccountType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SubAccountType

		annotation SummarizationSetBy = Automatic

	column x_AccountId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_AccountId

		annotation SummarizationSetBy = Automatic

	column x_AccountName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_AccountName

		annotation SummarizationSetBy = Automatic

	column x_AccountOwnerId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_AccountOwnerId

		annotation SummarizationSetBy = Automatic

	column x_BilledCostInUsd
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_BilledCostInUsd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_BilledUnitPrice
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_BilledUnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_BillingAccountAgreement
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_BillingAccountAgreement

		annotation SummarizationSetBy = Automatic

	column x_BillingAccountId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_BillingAccountId

		annotation SummarizationSetBy = Automatic

	column x_BillingAccountName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_BillingAccountName

		annotation SummarizationSetBy = Automatic

	column x_BillingExchangeRate
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_BillingExchangeRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_BillingExchangeRateDate
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: x_BillingExchangeRateDate

		annotation SummarizationSetBy = Automatic

	column x_BillingProfileId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_BillingProfileId

		annotation SummarizationSetBy = Automatic

	column x_BillingProfileName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_BillingProfileName

		annotation SummarizationSetBy = Automatic

	column x_ChargeId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ChargeId

		annotation SummarizationSetBy = Automatic

	column x_ContractedCostInUsd
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_ContractedCostInUsd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_CostAllocationRuleName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CostAllocationRuleName

		annotation SummarizationSetBy = Automatic

	column x_CostCategories
		dataType: string
		summarizeBy: none
		sourceColumn: x_CostCategories

		annotation SummarizationSetBy = Automatic

	column x_CostCenter
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CostCenter

		annotation SummarizationSetBy = Automatic

	column x_Credits
		dataType: string
		summarizeBy: none
		sourceColumn: x_Credits

		annotation SummarizationSetBy = Automatic

	column x_CostType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CostType

		annotation SummarizationSetBy = Automatic

	column x_CurrencyConversionRate
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_CurrencyConversionRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_CustomerId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CustomerId

		annotation SummarizationSetBy = Automatic

	column x_CustomerName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CustomerName

		annotation SummarizationSetBy = Automatic

	column x_Discount
		dataType: string
		summarizeBy: none
		sourceColumn: x_Discount

		annotation SummarizationSetBy = Automatic

	column x_EffectiveCostInUsd
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_EffectiveCostInUsd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_EffectiveUnitPrice
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_EffectiveUnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_ExportTime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: x_ExportTime

		annotation SummarizationSetBy = Automatic

	column x_IngestionTime
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: x_IngestionTime

		annotation SummarizationSetBy = Automatic

	column x_InvoiceIssuerId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_InvoiceIssuerId

		annotation SummarizationSetBy = Automatic

	column x_InvoiceSectionId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_InvoiceSectionId

		annotation SummarizationSetBy = Automatic

	column x_InvoiceSectionName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_InvoiceSectionName

		annotation SummarizationSetBy = Automatic

	column x_ListCostInUsd
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_ListCostInUsd

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_Location
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_Location

		annotation SummarizationSetBy = Automatic

	column x_Operation
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_Operation

		annotation SummarizationSetBy = Automatic

	column x_PartnerCreditApplied
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_PartnerCreditApplied

		annotation SummarizationSetBy = Automatic

	column x_PartnerCreditRate
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_PartnerCreditRate

		annotation SummarizationSetBy = Automatic

	column x_PricingBlockSize
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_PricingBlockSize

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_PricingSubcategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_PricingSubcategory

		annotation SummarizationSetBy = Automatic

	column x_PricingUnitDescription
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_PricingUnitDescription

		annotation SummarizationSetBy = Automatic

	column x_Project
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_Project

		annotation SummarizationSetBy = Automatic

	column x_PublisherCategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_PublisherCategory

		annotation SummarizationSetBy = Automatic

	column x_PublisherId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_PublisherId

		annotation SummarizationSetBy = Automatic

	column x_ResellerId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResellerId

		annotation SummarizationSetBy = Automatic

	column x_ResellerName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResellerName

		annotation SummarizationSetBy = Automatic

	column x_ResourceGroupName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResourceGroupName

		annotation SummarizationSetBy = Automatic

	column x_ResourceType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResourceType

		annotation SummarizationSetBy = Automatic

	column x_ServiceCode
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ServiceCode

		annotation SummarizationSetBy = Automatic

	column x_ServiceId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ServiceId

		annotation SummarizationSetBy = Automatic

	column x_ServicePeriodEnd
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: x_ServicePeriodEnd

		annotation SummarizationSetBy = Automatic

	column x_ServicePeriodStart
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: x_ServicePeriodStart

		annotation SummarizationSetBy = Automatic

	column x_SkuDescription
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuDescription

		annotation SummarizationSetBy = Automatic

	column x_SkuDetails
		dataType: string
		summarizeBy: none
		sourceColumn: x_SkuDetails

		annotation SummarizationSetBy = Automatic

	column x_SkuIsCreditEligible
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		summarizeBy: none
		sourceColumn: x_SkuIsCreditEligible

		annotation SummarizationSetBy = Automatic

	column x_SkuMeterCategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuMeterCategory

		annotation SummarizationSetBy = Automatic

	column x_SkuMeterId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuMeterId

		annotation SummarizationSetBy = Automatic

	column x_SkuMeterSubcategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuMeterSubcategory

		annotation SummarizationSetBy = Automatic

	column x_SkuOfferId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuOfferId

		annotation SummarizationSetBy = Automatic

	column x_SkuOrderId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuOrderId

		annotation SummarizationSetBy = Automatic

	column x_SkuOrderName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuOrderName

		annotation SummarizationSetBy = Automatic

	column x_SkuPartNumber
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuPartNumber

		annotation SummarizationSetBy = Automatic

	column x_SkuRegion
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuRegion

		annotation SummarizationSetBy = Automatic

	column x_SkuServiceFamily
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuServiceFamily

		annotation SummarizationSetBy = Automatic

	column x_SkuTerm
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: x_SkuTerm

		annotation SummarizationSetBy = Automatic

	column x_SkuTier
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuTier

		annotation SummarizationSetBy = Automatic

	column x_SourceChanges
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SourceChanges

		annotation SummarizationSetBy = Automatic

	column x_SourceName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SourceName

		annotation SummarizationSetBy = Automatic

	column x_SourceProvider
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SourceProvider

		annotation SummarizationSetBy = Automatic

	column x_SourceType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SourceType

		annotation SummarizationSetBy = Automatic

	column x_SourceVersion
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SourceVersion

		annotation SummarizationSetBy = Automatic

	column x_UsageType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_UsageType

		annotation SummarizationSetBy = Automatic

	column x_SkuCoreCount
		dataType: int64
		formatString: 0
		sourceProviderType: int
		summarizeBy: sum
		sourceColumn: x_SkuCoreCount

		annotation SummarizationSetBy = Automatic

	column x_ConsumedCoreHours
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_ConsumedCoreHours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_SkuLicenseStatus
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuLicenseStatus

		annotation SummarizationSetBy = Automatic

	column x_SkuLicenseType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuLicenseType

		annotation SummarizationSetBy = Automatic

	column x_SkuLicenseQuantity
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		summarizeBy: sum
		sourceColumn: x_SkuLicenseQuantity

		annotation SummarizationSetBy = Automatic

	column x_SkuLicenseUnit
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuLicenseUnit

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountKey
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountKey

		annotation SummarizationSetBy = Automatic

	column x_ToolkitTool
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ToolkitTool

		annotation SummarizationSetBy = Automatic

	column x_ToolkitVersion
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ToolkitVersion

		annotation SummarizationSetBy = Automatic

	column x_ResourceParentId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResourceParentId

		annotation SummarizationSetBy = Automatic

	column x_ResourceParentName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResourceParentName

		annotation SummarizationSetBy = Automatic

	column x_ResourceParentType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResourceParentType

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountNameUnique
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CommitmentDiscountNameUnique

		annotation SummarizationSetBy = Automatic

	column ResourceNameUnique
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ResourceNameUnique

		annotation SummarizationSetBy = Automatic

	column SubAccountNameUnique
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SubAccountNameUnique

		annotation SummarizationSetBy = Automatic

	column x_ChargeMonth
		dataType: dateTime
		formatString: Mmm yyyy
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: x_ChargeMonth

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column x_CommitmentDiscountSavings
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_CommitmentDiscountSavings

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_CommitmentDiscountUtilizationAmount
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_CommitmentDiscountUtilizationAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_CommitmentDiscountUtilizationPotential
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_CommitmentDiscountUtilizationPotential

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_NegotiatedDiscountSavings
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_NegotiatedDiscountSavings

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_ResourceGroupNameUnique
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ResourceGroupNameUnique

		annotation SummarizationSetBy = Automatic

	column x_SkuUsageType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuUsageType

		annotation SummarizationSetBy = Automatic

	column x_TotalSavings
		dataType: double
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_TotalSavings

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_ReportingDate
		dataType: dateTime
		formatString: Mmm yyyy
		sourceProviderType: datetimeoffset
		summarizeBy: none
		sourceColumn: x_ReportingDate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column x_SkuTermLabel
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuTermLabel

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountPercent
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_CommitmentDiscountPercent

		annotation SummarizationSetBy = Automatic

	column x_NegotiatedDiscountPercent
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_NegotiatedDiscountPercent

		annotation SummarizationSetBy = Automatic

	column x_TotalDiscountPercent
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		sourceProviderType: decimal
		summarizeBy: sum
		sourceColumn: x_TotalDiscountPercent

		annotation SummarizationSetBy = Automatic

	column x_FreeReason
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_FreeReason

		annotation SummarizationSetBy = Automatic

	column x_ResourceTop1K
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		sourceProviderType: bit
		summarizeBy: none
		sourceColumn: x_ResourceTop1K

		annotation SummarizationSetBy = Automatic

	column tag_Application
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Application

		annotation SummarizationSetBy = Automatic

	column tag_BusinessUnit
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_BusinessUnit

		annotation SummarizationSetBy = Automatic

	column tag_CostCenter
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_CostCenter

		annotation SummarizationSetBy = Automatic

	column tag_Department
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Department

		annotation SummarizationSetBy = Automatic

	column tag_Division
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Division

		annotation SummarizationSetBy = Automatic

	column tag_Env
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Env

		annotation SummarizationSetBy = Automatic

	column tag_Owner
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Owner

		annotation SummarizationSetBy = Automatic

	column tag_Product
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Product

		annotation SummarizationSetBy = Automatic

	column tag_Project
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Project

		annotation SummarizationSetBy = Automatic

	column tag_Purpose
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Purpose

		annotation SummarizationSetBy = Automatic

	column tag_Service
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_Service

		annotation SummarizationSetBy = Automatic

	column CapacityReservationId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CapacityReservationId

		annotation SummarizationSetBy = Automatic

	column CapacityReservationStatus
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CapacityReservationStatus

		annotation SummarizationSetBy = Automatic

	column CommitmentDiscountQuantity
		dataType: double
		sourceProviderType: double
		summarizeBy: sum
		sourceColumn: CommitmentDiscountQuantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CommitmentDiscountUnit
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: CommitmentDiscountUnit

		annotation SummarizationSetBy = Automatic

	column InvoiceId
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: InvoiceId

		annotation SummarizationSetBy = Automatic

	column PricingCurrency
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: PricingCurrency

		annotation SummarizationSetBy = Automatic

	column ServiceSubcategory
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: ServiceSubcategory

		annotation SummarizationSetBy = Automatic

	column SkuMeter
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SkuMeter

		annotation SummarizationSetBy = Automatic

	column SkuPriceDetails
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: SkuPriceDetails

		annotation SummarizationSetBy = Automatic

	column x_AmortizationClass
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_AmortizationClass

		annotation SummarizationSetBy = Automatic

	column x_BillingItemCode
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_BillingItemCode

		annotation SummarizationSetBy = Automatic

	column x_BillingItemName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_BillingItemName

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountNormalizedRatio
		dataType: double
		sourceProviderType: double
		summarizeBy: sum
		sourceColumn: x_CommitmentDiscountNormalizedRatio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column x_CommitmentDiscountSpendEligibility
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountSpendEligibility

		annotation SummarizationSetBy = Automatic

	column x_CommitmentDiscountUsageEligibility
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CommitmentDiscountUsageEligibility

		annotation SummarizationSetBy = Automatic

	column x_CommodityCode
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CommodityCode

		annotation SummarizationSetBy = Automatic

	column x_CommodityName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_CommodityName

		annotation SummarizationSetBy = Automatic

	column x_ComponentName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ComponentName

		annotation SummarizationSetBy = Automatic

	column x_ComponentType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ComponentType

		annotation SummarizationSetBy = Automatic

	column x_InstanceID
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_InstanceID

		annotation SummarizationSetBy = Automatic

	column x_OwnerAccountID
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_OwnerAccountID

		annotation SummarizationSetBy = Automatic

	column x_ServiceModel
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_ServiceModel

		annotation SummarizationSetBy = Automatic

	column x_SkuInstanceType
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuInstanceType

		annotation SummarizationSetBy = Automatic

	column x_SkuLicenseUnusedQuantity
		dataType: int64
		formatString: 0
		sourceProviderType: bigint
		summarizeBy: sum
		sourceColumn: x_SkuLicenseUnusedQuantity

		annotation SummarizationSetBy = Automatic

	column x_SkuOperatingSystem
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuOperatingSystem

		annotation SummarizationSetBy = Automatic

	column x_SkuPlanName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SkuPlanName

		annotation SummarizationSetBy = Automatic

	column x_SubproductName
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: x_SubproductName

		annotation SummarizationSetBy = Automatic

	column x_SourceValues
		dataType: string
		summarizeBy: none
		sourceColumn: x_SourceValues

		annotation SummarizationSetBy = Automatic

	column tag_account_coding
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_account_coding

		annotation SummarizationSetBy = Automatic

	column tag_billing_group
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_billing_group

		annotation SummarizationSetBy = Automatic

	column tag_ministry_name
		dataType: string
		sourceProviderType: nvarchar(max)
		summarizeBy: none
		sourceColumn: tag_ministry_name

		annotation SummarizationSetBy = Automatic

	hierarchy 'Service Hierarchy'

		level ServiceCategory
			column: ServiceCategory

		level ServiceName
			column: ServiceName

		level ResourceType
			column: ResourceType

	partition Costs = m
		mode: directQuery
		queryGroup: 'Data Explorer'
		source =
				let
				    // Customize the following settings to tune how tags are handled
				
				        // Set the tags you want to promote as 'tag_*' columns in this array
				        PromotedTags = {"Application", "BusinessUnit", "CostCenter", "Department", "Division", "Env", "Owner", "Product", "Project", "Purpose", "Service", "account_coding", "billing_group", "ministry_name"},
				
				        // This option matches tag keys that may have different case (for example, 'env' and 'ENV')
				        // NOTE: This option slows down the query significantly. Disable it if tag queries are failing.
				        Handle_mixed_case_tags = true,
				
				        // This option removes any unwanted spaces before or after the tag key
				        // NOTE: This option slows down the query significantly. Disable it if tag queries are failing.
				        Trim_spaces_from_tags = true,
				
				    // Init report parameters
				    lookback = Text.From(if #"Number of Months" = "" or #"Number of Months" = null then 999 else #"Number of Months"),
				    Source = AzureDataExplorer.Contents(#"Cluster URL", "Hub", "
				
				
				    Costs_v1_2
				    //
				    // Apply summarization settings
				    | where ChargePeriodStart >= monthsago(" & lookback & ")
				    | as filteredCosts
					| extend x_ChargeMonth = startofmonth(ChargePeriodStart)
					| extend x_ReportingDate = " & (if (#"Default Granularity" = "Monthly") then "x_ChargeMonth" else "startofday(ChargePeriodStart)") & "
				    //
				    // SKU details
				    | extend x_SkuUsageType = tostring(coalesce(SkuPriceDetails.x_UsageType, x_SkuDetails.UsageType))
				    | extend x_SkuLicenseUnusedQuantity = x_SkuLicenseQuantity - x_SkuCoreCount
				    //
				    // Commitment discounts
				    | extend x_CommitmentDiscountKey = iff(isempty(x_SkuInstanceType), '', strcat(x_SkuInstanceType, x_SkuMeterId))
				    | extend x_SkuTermLabel = case(isempty(x_SkuTerm) or x_SkuTerm <= 0, '', x_SkuTerm < 12, strcat(x_SkuTerm, ' month', iff(x_SkuTerm != 1, 's', '')), strcat(x_SkuTerm / 12, ' year', iff(x_SkuTerm != 12, 's', '')))
				    //
				    // CSP partners
				    // x_PartnerBilledCredit = iff(x_PartnerCreditApplied, BilledCost * x_PartnerCreditRate, todouble(0))
				    // x_PartnerEffectiveCredit = iff(x_PartnerCreditApplied, EffectiveCost * x_PartnerCreditRate, todouble(0))
				    //
				    // Toolkit
				    | extend x_ToolkitTool = tostring(Tags['ftk-tool'])
				    | extend x_ToolkitVersion = tostring(Tags['ftk-version'])
				    | extend tmp_ResourceParent = database('Ingestion').parse_resourceid(Tags['cm-resource-parent'])
				    | extend x_ResourceParentId = tostring(tmp_ResourceParent.ResourceId)
				    | extend x_ResourceParentName = tostring(tmp_ResourceParent.ResourceName)
				    | extend x_ResourceParentType = tostring(tmp_ResourceParent.ResourceType)
				    //
				    // TODO: Only add differentiators when the name is not unique
				    | extend CommitmentDiscountNameUnique = iff(isempty(CommitmentDiscountId), '', strcat(CommitmentDiscountName, ' (', CommitmentDiscountType, ')'))
				    | extend ResourceNameUnique           = iff(isempty(ResourceId),           '', strcat(ResourceName,           ' (', ResourceType, ')'))
				    | extend x_ResourceGroupNameUnique    = iff(isempty(x_ResourceGroupName),  '', strcat(x_ResourceGroupName,    ' (', SubAccountName, ')'))
				    | extend SubAccountNameUnique         = iff(isempty(SubAccountId),         '', strcat(SubAccountName,         ' (', split(SubAccountId, '/')[3], ')'))
				    //
				    // Explain why cost is 0
				    | extend x_FreeReason = case(
				        BilledCost != 0.0 or EffectiveCost != 0.0, '',
				        PricingCategory == 'Committed', strcat('Unknown ', CommitmentDiscountStatus, ' Commitment'),
				        x_BilledUnitPrice == 0.0 and x_EffectiveUnitPrice == 0.0 and ContractedUnitPrice == 0.0 and ListUnitPrice == 0.0 and isempty(CommitmentDiscountType), case(
				            x_SkuDescription contains 'Trial', 'Trial',
				            x_SkuDescription contains 'Preview', 'Preview',
				            'Other'
				        ),
				        x_BilledUnitPrice > 0.0 or x_EffectiveUnitPrice > 0.0, case(
				            PricingQuantity > 0.0, 'Low Usage',
				            PricingQuantity == 0.0, 'No Usage',
				            'Unknown Negative Quantity'
				        ),
				        'Unknown'
				    )
				    //" & (if List.Count(PromotedTags) > 0 then (
				        if Handle_mixed_case_tags or Trim_spaces_from_tags then ("
				            | extend keys = bag_keys(Tags)
				            | extend cleankeys = " & (
				                if Handle_mixed_case_tags and Trim_spaces_from_tags then "parse_json(replace_string(tolower(keys), ' ', ''))"
				                else if Handle_mixed_case_tags                      then "parse_json(tolower(keys))"
				                else if Trim_spaces_from_tags                       then "parse_json(replace_string(keys, ' ', ''))"
				                else "keys"
				            ) & "
				            | extend " & Text.Combine(List.Transform(PromotedTags, each "tag_" & Text.Replace(_, " ", "") & " = iff(array_index_of(cleankeys, tolower('" & _ & "')) < 0, '', tostring(Tags[tostring(keys[toint(array_index_of(cleankeys, tolower('" & _ & "')))])]))"), ", ") & "
				            | project-away keys, cleankeys"
				        ) else ("
				            | extend " & Text.Combine(List.Transform(PromotedTags, each "tag_" & Text.Replace(_, " ", "") & " = tostring(Tags['" & _ & "'])"), ", ")
				        )
				    ) else "") & "
				    //
				    | extend SkuPriceDetails = tostring(SkuPriceDetails)
				    | extend Tags = tostring(Tags)
				    | extend x_SkuDetails = tostring(x_SkuDetails)
				    //
				    | extend x_ResourceTop1K = ChargeCategory != 'Usage' or isempty(ResourceId) or ResourceId in (
				        filteredCosts
				        | where isnotempty(ResourceId) and ChargeCategory == 'Usage'
				        | summarize sum(EffectiveCost) by ResourceId
				        | order by sum_EffectiveCost desc
				        | limit 1000
				        | distinct ResourceId
				    )
				    //
				    | project-away tmp_ResourceParent
				
				
				    ", [MaxRows=null, MaxSize=null, NoTruncate=null, AdditionalSetStatements=null]),
				
				    // Sort columns alphabetically
				    Output = Table.ReorderColumns(Source, List.Sort(Table.ColumnNames(Source)))
				in
				    Output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

