output "management_group_names" {
  description = "Expected management group names generated by this module's architecture naming model."
  value       = local.management_group_names
}

output "management_group_resource_ids" {
  description = "Management group resource IDs created by AVM ALZ core module."
  value       = module.alz.management_group_resource_ids
}

output "policy_assignment_identity_ids" {
  description = "Managed identity principal IDs created for ALZ policy assignments."
  value       = module.alz.policy_assignment_identity_ids
}

output "management_resource_id" {
  description = "Resource group ID for management resources from AVM management module."
  value       = module.management_resources.resource_id
}

output "management_log_analytics_workspace_id" {
  description = "Log Analytics workspace ID from AVM management module."
  value = try(
    module.management_resources.log_analytics_workspace_resource_id,
    module.management_resources.azurerm_log_analytics_workspace,
    null
  )
}

output "connectivity_virtual_wan_outputs" {
  description = "Pass-through outputs from AVM connectivity virtual-wan module."
  value       = module.connectivity_virtual_wan
}
