variables:
  - name: policyDocAdditionalBuiltInPolicyMetadataConfigFilePath
    value: "azure_policy_lens/configurations/additional-policy-metadata-config.jsonc"
  - name: policyDocCustomSecurityControlPath
    value: "security-controls"
  - name: policyDocGitHubDomainName
    value: "github.com"
  - name: policyDocExemptionExpiresOnWarningDays
    value: 30
  - name: policyDocComplianceWarningPercentageThreshold
    value: 80
  - name: policyDocDiscoveryFileName
    value: "EnvironmentDiscovery.zip"
